CREATE SEQUENCE Supplier_seq
START WITH 1
INCREMENT BY 1;
SELECT NEXT VALUE FOR Supplier_seq

CREATE SEQUENCE Product_seq
START WITH 1
INCREMENT BY 1;
SELECT NEXT VALUE FOR  Product_seq
ALTER SEQUENCE Product_seq
RESTART WITH 17;

CREATE SEQUENCE Customer_seq
START WITH 1
INCREMENT BY 1;
ALTER SEQUENCE Customer_seq
RESTART WITH 10;

CREATE SEQUENCE Order_seq
START WITH 1
INCREMENT BY 1;
ALTER SEQUENCE Order_seq
RESTART WITH 7;
