CREATE FUNCTION GENERATE_ID
(
@CHAR CHAR,
@NUM INT
)
RETURNS VARCHAR(5)
AS
BEGIN
   DECLARE @ID VARCHAR(5)
   SET @ID=@CHAR + RIGHT('0000'+CAST(@NUM AS VARCHAR(4)),4)
   RETURN @ID
END

SELECT DBO.GENERATE_ID('S',12)
